### ISSUE TITLE
Fish git prompt displays errors when in detached state

### ISSUE THREAD

**Issue by joshhunt** [orefalo/g2#9]
When I'm in a detached state in a git repo, my git prompt displays:

```
test: Unexpected argument type at index 0
test: Missing argument at index 2
test: Missing argument at index 2
~/D/s/MyRepo (➦ detached:[78b67a7]) →
```

Error is a bit unhelpful as it doesn't mention line numbers...

[Here's my full prompt file](https://gist.github.com/joshhunt/54a1151b3f58144db214), it's currently a bit modified from the original, but I was getting the errors before I made my changes.

I'm running fish v2.1.1 and git version 1.9.3 (Apple Git-50)

**Comment by orefalo** [comment]
issue fixed
